export enum actionTypes {
    GET_COFFEE = 'GET_COFFEE',
    FETCH_COFFEE_BEGIN   = 'FETCH_COFFEE_BEGIN',
    FETCH_COFFEE_SUCCESS = 'FETCH_COFFEE_SUCCESS',
    FETCH_COFFEE_FAILURE = 'FETCH_COFFEE_FAILURE'
}